version: "3.8"

services:
  # Frontend service
  client:
    image: ghcr.io/kmmedia/kmmedia-course-registration/client:staging
    ports:
      - "3000:80"
    depends_on:
      - server
    environment:
      - REACT_APP_API_URL=https://api-staging.kmmediatraininginstitute.com
    networks:
      - app-network
    restart: unless-stopped

  # Backend service
  server:
    image: ghcr.io/kmmedia/kmmedia-course-registration/server:staging
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=staging
      - PORT=5000
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRES_IN=24h
      - DB_PATH=./database.sqlite
      - RATE_LIMIT_WINDOW_MS=900000
      - RATE_LIMIT_MAX_REQUESTS=100
    volumes:
      - server-data:/app/database
    networks:
      - app-network
    restart: unless-stopped

  # Nginx reverse proxy
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/staging.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - client
      - server
    networks:
      - app-network
    restart: unless-stopped

volumes:
  server-data:

networks:
  app-network:
    driver: bridge
