version: "3.8"

services:
  # Frontend service
  client:
    image: ghcr.io/kmmedia/kmmedia-course-registration/client:latest
    ports:
      - "3000:80"
    depends_on:
      - server
    environment:
      - REACT_APP_API_URL=https://api.kmmediatraininginstitute.com
    networks:
      - app-network
    restart: unless-stopped
    deploy:
      replicas: 2
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  # Backend service
  server:
    image: ghcr.io/kmmedia/kmmedia-course-registration/server:latest
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRES_IN=24h
      - DB_PATH=./database.sqlite
      - RATE_LIMIT_WINDOW_MS=900000
      - RATE_LIMIT_MAX_REQUESTS=100
    volumes:
      - server-data:/app/database
    networks:
      - app-network
    restart: unless-stopped
    deploy:
      replicas: 2
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

  # Nginx reverse proxy
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/production.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - client
      - server
    networks:
      - app-network
    restart: unless-stopped
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M

  # Database backup service
  backup:
    image: alpine:latest
    volumes:
      - server-data:/data
      - ./backups:/backups
    command: |
      sh -c "
        while true; do
          sleep 86400
          cp /data/database.sqlite /backups/database-$(date +%Y%m%d-%H%M%S).sqlite
          find /backups -name 'database-*.sqlite' -mtime +7 -delete
        done
      "
    networks:
      - app-network
    restart: unless-stopped

volumes:
  server-data:

networks:
  app-network:
    driver: bridge
