version: "3.8"

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: kmmedia-postgres
    environment:
      POSTGRES_DB: kmmedia
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - kmmedia-network
    restart: unless-stopped

  # Backend Server
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    container_name: kmmedia-server
    environment:
      - NODE_ENV=development
      - PORT=5000
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=kmmedia
      - DB_USER=postgres
      - DB_PASSWORD=postgres123
      - DATABASE_URL=postgresql://postgres:postgres123@postgres:5432/kmmedia
      - JWT_SECRET=your-super-secret-jwt-key-change-this-in-production
      - JWT_EXPIRES_IN=24h
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app
      - /app/node_modules
    depends_on:
      - postgres
    networks:
      - kmmedia-network
    restart: unless-stopped

  # Frontend Client
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    container_name: kmmedia-client
    environment:
      - REACT_APP_API_URL=http://localhost:5000
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - server
    networks:
      - kmmedia-network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  kmmedia-network:
    driver: bridge
