server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: app-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: kmmedia-app
          __path__: /var/log/app/*.log

    pipeline_stages:
      - match:
          selector: '{job="kmmedia-app"}'
          stages:
            - regex:
                expression: '^(?P<timestamp>\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}) \[(?P<level>\w+)\]: (?P<message>.*)'
            - timestamp:
                source: timestamp
                format: "2006-01-02 15:04:05"
            - labels:
                level:
                message:
            - output:
                source: message

  - job_name: access-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: kmmedia-access
          __path__: /var/log/app/access-*.log

    pipeline_stages:
      - match:
          selector: '{job="kmmedia-access"}'
          stages:
            - json:
                expressions:
                  timestamp: timestamp
                  method: method
                  url: url
                  statusCode: statusCode
                  duration: duration
                  userAgent: userAgent
            - timestamp:
                source: timestamp
                format: RFC3339
            - labels:
                method:
                statusCode:
                duration:
                userAgent:
